theme = 'soho'

baseurl = "https://fullstackbio.de/"
languageCode = "en"
title = "Full Stack Bioinformatics"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]
disable_share = true

[params]
title = "Full Stack Bioinformatics"
description = "From transistors to biomedical insight"
# gravatar = "soho@example.com"
images = ["images/profile.jpg"]
profilePicture = "images/profile.jpg"
copyright = "Manuel Holtgrewe"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["posts"]
customCss = ["/css/custom.css"]
disable_share = true

# Set custom theme color.
themeColor = "#878B94"
# #BEC8C0
# #E7E9DC
# #F1F2EE

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/manuel-holtgrewe/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/holtgrewe"


[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 300
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 400
  identifier = "tags"
  url = "/tags/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
